resources:
  - persistentVolumeClaim.yaml
  - serviceaccount.yaml
  - encoding-configmap.yaml
  - deployment.yaml
  - service.yaml
patches:
  - path: patch-encoding-init.yaml
  - path: patch-graceful-shutdown.yaml
