---
# Source: jellyfin/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    helm.sh/chart: jellyfin-2.3.0
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "10.10.6"
    app.kubernetes.io/managed-by: Helm
  annotations:
    metallb.universe.tf/allow-shared-ip: media-shared
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.226
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: release-name
