apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-nfs-media
  labels:
    app: jellyfin
    app.kubernetes.io/name: jellyfin
spec:
  capacity:
    storage: 500Gi  # Arbitrary; doesn't restrict actual size
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.15
    path: /mnt/tank/media
  persistentVolumeReclaimPolicy: Retain
