apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: media
  labels:
    app: jellyfin
    app.kubernetes.io/name: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: jellyfin-nfs-media
