---
# Source: nzbget/templates/common.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-nzbget-config
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/version: v21.1
    helm.sh/chart: nzbget-12.4.2
  annotations:
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "k8s-nfs"
---
# Source: nzbget/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-nzbget
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/version: v21.1
    helm.sh/chart: nzbget-12.4.2
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 6789
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/instance: release-name
---
# Source: nzbget/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-nzbget
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nzbget
    app.kubernetes.io/version: v21.1
    helm.sh/chart: nzbget-12.4.2
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nzbget
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nzbget
        app.kubernetes.io/instance: release-name
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: release-name-nzbget
          image: "ghcr.io/elfhosted:25.2@sha256:aab5814cc7a89ca4ad04b62d8e7b98725b15697bf711c9982bbcd3fc55d1aab1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6789
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
          livenessProbe:
            tcpSocket:
              port: 6789
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6789
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 6789
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: release-name-nzbget-config
        - name: media
          persistentVolumeClaim:
            claimName: jellyfin-media
