image:
  repository: ghcr.io/mithr4ndir/nzbget
  tag: "21.1.1"
  pullPolicy: IfNotPresent

# remove if your GHCR package is public
imagePullSecrets:
  - name: ghcr-pull

service:
  main:
    annotations:
      metallb.universe.tf/allow-shared-ip: media-shared
    type: LoadBalancer
    loadBalancerIP: 192.168.1.226
    externalTrafficPolicy: Cluster
    ports:
      main:
        port: 10057
        targetPort: http       # <- chart maps this to containerPort name

persistence:
  config:
    enabled: true
    mountPath: "/config"
    storageClass: k8s-nfs
    size: 1Gi
  media:
    enabled: true
    existingClaim: "jellyfin-media"
    mountPath: "/downloads"
    subPath: downloads        # <- /mnt/tank/media/downloads

workload:
  main:
    podSpec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        main:
          env:
            TZ: "America/Los_Angeles"  # adjust
            PUID: "1000"
            PGID: "1000"
            UMASK: "002"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet: { path: "/", port: 6789 }
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet: { path: "/", port: 6789 }
            startup:
              enabled: false
