namespace: media
resources:
  - media-namespace.yaml
  - media-pv-nfs.yaml
  - media-pvc.yaml
  - jellyfin-external-svc.yaml
  - nzbget/
  - qbittorrent/
  - radarr/
  - sonarr/
  - prowlarr/
  - jellyseer/
  - bazarr/