apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: metallb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: controller
  template:
    metadata:
      labels:
        component: controller
    spec:
      serviceAccountName: controller
      containers:
        - name: controller
          image: quay.io/metallb/controller:v0.15.2
          imagePullPolicy: IfNotPresent
