apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-infrastructure
spec:
  provider:
    onepasswordSDK:
      vault: Infrastructure
      auth:
        serviceAccountSecretRef:
          name: onepassword-service-account-token
          key: token
          namespace: external-secrets
