---
# Source: reloader/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-namespace: "reloader"
    meta.helm.sh/release-name: "reloader"
  labels:
    app: reloader-reloader
    release: "reloader"
    app.kubernetes.io/name: reloader
    app.kubernetes.io/instance: "reloader"
    helm.sh/chart: "reloader-2.2.9"
    chart: "reloader-2.2.9"
    heritage: "Helm"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "v1.4.14"
  name: reloader-reloader
  namespace: reloader
