apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media
  labels:
    app: media
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.15
    path: /mnt/tank/media
