apiVersion: apps/v1
kind: Deployment
metadata:
  name: dream-team-dream-team-web
  namespace: automation
  labels:
    app.kubernetes.io/name: dream-team
    app.kubernetes.io/instance: dream-team
    app.kubernetes.io/version: 0.1.4
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: dream-team
    app.kubernetes.io/part: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dream-team
      app.kubernetes.io/part: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dream-team
        app.kubernetes.io/instance: dream-team
        app.kubernetes.io/version: 0.1.4
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: dream-team
        app.kubernetes.io/part: web
    spec:
      securityContext:
        fsGroup: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: web
        image: ghcr.io/mithr4ndir/palantir-nq:0.1.4
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        command:
        - uvicorn
        - nq_ibb.forward.dream_team_web:app
        - --host
        - 0.0.0.0
        - --port
        - '8080'
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - secretRef:
            name: dream-team-dream-team-secrets
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
