apiVersion: v1
kind: Service
metadata:
  name: dream-team-dream-team-web
  namespace: automation
  labels:
    app.kubernetes.io/name: dream-team
    app.kubernetes.io/instance: dream-team
    app.kubernetes.io/version: 0.1.3
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: dream-team
    app.kubernetes.io/part: web
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.235
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: dream-team
    app.kubernetes.io/part: web
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
