---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-custom-config
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - source_matchers:
          - severity = critical
        target_matchers:
          - severity =~ warning|info
        equal: [namespace, alertname]
      - source_matchers:
          - severity = warning
        target_matchers:
          - severity = info
        equal: [namespace, alertname]
      - source_matchers:
          - alertname = InfoInhibitor
        target_matchers:
          - severity = info
        equal: [namespace]
      - target_matchers:
          - alertname = InfoInhibitor
    route:
      receiver: discord
      group_by: [namespace, alertname]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
        - matchers:
            - alertname = "Watchdog"
          receiver: "null"
        - matchers:
            - alertname =~ "InfoInhibitor|KubeVersionMismatch"
          receiver: "null"
        - matchers:
            - alertname = "NodeDown"
          receiver: discord
          group_by: [hypervisor, alertname]
          group_wait: 1m
          repeat_interval: 1h
        - matchers:
            - alertname = "PveGuestDown"
          receiver: discord
          group_by: [alertname, node]
          group_wait: 1m
        - matchers:
            - severity = critical
          receiver: discord
          repeat_interval: 1h
    receivers:
      - name: "null"
      - name: discord
        webhook_configs:
          - send_resolved: true
            url: "http://discord-alert-proxy.monitoring.svc:9095/webhook"
