---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elasticsearch-credentials
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-infrastructure
    kind: ClusterSecretStore
  target:
    name: elasticsearch-credentials
  data:
    - secretKey: username
      remoteRef:
        # 1Password item: "Elasticsearch - Grafana User"
        key: "tdrfzz3fgjyttrl7uj2mtlqbvi/username"
    - secretKey: password
      remoteRef:
        # 1Password item: "Elasticsearch - Grafana User"
        key: "tdrfzz3fgjyttrl7uj2mtlqbvi/password"
