---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-infrastructure
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
    creationPolicy: Owner
  data:
    - secretKey: GF_DATABASE_PASSWORD
      remoteRef:
        key: "sa6nzukej6enqh5rwdxeng7o4u/password"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: WAZUH_OPENSEARCH_PASSWORD
      remoteRef:
        key: "vll2ijfibrg23bahn3jyfatnui/indexer_admin_password"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
