---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: healthchecks-watchdog
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-infrastructure
    kind: ClusterSecretStore
  target:
    name: healthchecks-watchdog
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: "zr7mrafo64zpf7usc2ah5nso2a/credential"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
