resources:
  - namespace.yaml
  - application.yaml
  - prometheus-external-svc.yaml
  - alertmanager-config.yaml
  - prometheus-file-sd-configmap.yaml
  - loki-external-svc.yaml
  - vector-aggregator-svc.yaml
  - discord-alert-proxy
