resources:
  - namespace.yaml
  - application.yaml
  - prometheus-external-svc.yaml
  - alertmanager-config.yaml
  - loki-external-svc.yaml
  - vector-aggregator-svc.yaml
  - grafana-externalsecret.yaml
  - grafana-dashboards
  - discord-alert-proxy
