apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-file-sd-targets
  namespace: monitoring
data:
  vm-targets.json: |
    [
      {"targets": ["192.168.1.88:9100"], "labels": {"instance": "cmd_center1"}},
      {"targets": ["192.168.1.89:9100"], "labels": {"instance": "k8cluster2"}},
      {"targets": ["192.168.1.90:9100"], "labels": {"instance": "k8cluster1"}},
      {"targets": ["192.168.1.91:9100"], "labels": {"instance": "k8cluster3"}},
      {"targets": ["192.168.1.92:9100"], "labels": {"instance": "nginx1"}},
      {"targets": ["192.168.1.93:9100"], "labels": {"instance": "nginx2"}},
      {"targets": ["192.168.1.121:9100"], "labels": {"instance": "grafana"}},
      {"targets": ["192.168.1.122:9100"], "labels": {"instance": "timescaledb"}},
      {"targets": ["192.168.1.150:9100"], "labels": {"instance": "npm"}},
      {"targets": ["192.168.1.170:9100"], "labels": {"instance": "jellyfin"}},
      {"targets": ["192.168.1.171:9100"], "labels": {"instance": "wazuh"}},
      {"targets": ["192.168.1.10:9100"], "labels": {"instance": "pve"}},
      {"targets": ["192.168.1.11:9100"], "labels": {"instance": "pve2"}},
      {"targets": ["192.168.1.15:9100"], "labels": {"instance": "truenas"}}
    ]
