---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snmp-exporter-config
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword-infrastructure
    kind: ClusterSecretStore
  target:
    name: snmp-exporter-config
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        snmp.yml: |
          auths:
            switch_v2c:
              version: 2
              community: "{{ .community }}"
          modules:
            if_mib:
              walk:
                - sysUpTime
                - interfaces
                - ifXTable
              lookups:
                - source_indexes: [ifIndex]
                  lookup: ifAlias
                - source_indexes: [ifIndex]
                  lookup: ifDescr
                - source_indexes: [ifIndex]
                  lookup: ifName
              overrides:
                ifAlias:
                  ignore: true
                ifDescr:
                  ignore: true
                ifName:
                  type: DisplayString
                ifType:
                  type: EnumAsInfo
  data:
    - secretKey: community
      remoteRef:
        key: "ie2ggejxa6kfepuhxdvggvsymm/community"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
