apiVersion: v1
kind: Service
metadata:
  name: vector-aggregator-external
  namespace: monitoring
  labels:
    app: vector-aggregator-external
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.232
  ports:
    - port: 5514
      targetPort: 5514
      protocol: TCP
      name: syslog
    - port: 6000
      targetPort: 6000
      protocol: TCP
      name: vector
  selector:
    app.kubernetes.io/instance: vector-aggregator
    app.kubernetes.io/name: vector
