---
# Source: nfs-subdir-external-provisioner/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-nfs-subdir-external-provisioner
  labels:
    chart: nfs-subdir-external-provisioner-4.0.18
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: release-name
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
      release: release-name
  template:
    metadata:
      annotations:
      labels:
        app: nfs-subdir-external-provisioner
        release: release-name
    spec:
      serviceAccountName: release-name-nfs-subdir-external-provisioner
      securityContext:
        {}
      containers:
        - name: nfs-subdir-external-provisioner
          image: "registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2"
          imagePullPolicy: IfNotPresent
          securityContext:
            {}
          volumeMounts:
            - name: nfs-subdir-external-provisioner-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cluster.local/release-name-nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: 192.168.1.15
            - name: NFS_PATH
              value: /mnt/tank/k8s
      volumes:
        - name: nfs-subdir-external-provisioner-root
          persistentVolumeClaim:
            claimName: pvc-release-name-nfs-subdir-external-provisioner
