---
# Source: nfs-subdir-external-provisioner/templates/persistentvolumeclaim.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-release-name-nfs-subdir-external-provisioner
  labels:
    chart: nfs-subdir-external-provisioner-4.0.18
    heritage: Helm
    app: nfs-subdir-external-provisioner
    release: release-name
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  selector:
    matchLabels:
      nfs-subdir-external-provisioner: release-name-nfs-subdir-external-provisioner
  resources:
    requests:
      storage: 10Mi
