---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: science-quota
  namespace: science
spec:
  hard:
    limits.cpu: "18"
    limits.memory: 36Gi
    requests.cpu: "18"
    requests.memory: 36Gi
