apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: donchian-signal-donchian-signal-secrets
  namespace: automation
  labels:
    app.kubernetes.io/name: donchian-signal
    app.kubernetes.io/instance: donchian-signal
    app.kubernetes.io/version: 0.1.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: signal-generator
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-infrastructure
  target:
    name: donchian-signal-donchian-signal-secrets
    creationPolicy: Owner
  data:
  - secretKey: DONCHIAN_DISCORD_WEBHOOK
    remoteRef:
      key: rmmf24ed3vvjffafar6wtah4ky/webhook_url
  - secretKey: NQ_IBB_DB_URL
    remoteRef:
      key: 6quj7qxa3kzp2nwabtsh5drpd4/dsn
