---
# Source: app-template/templates/common.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-config
  labels:
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: qbittorrent
    helm.sh/chart: app-template-3.5.1
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "k8s-nfs"
---
# Source: app-template/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/service: qbittorrent
    helm.sh/chart: app-template-3.5.1
  annotations:
    metallb.universe.tf/allow-shared-ip: media-shared
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.226
  ports:
    - port: 8080
      targetPort: webui
      protocol: TCP
      name: webui
    - port: 6881
      targetPort: bittorrent-tcp
      protocol: TCP
      name: bittorrent-tcp
    - port: 6881
      targetPort: bittorrent-udp
      protocol: UDP
      name: bittorrent-udp
  selector:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/name: qbittorrent
---
# Source: app-template/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: qbittorrent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: qbittorrent
    helm.sh/chart: app-template-3.5.1
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: main
      app.kubernetes.io/name: qbittorrent
      app.kubernetes.io/instance: qbittorrent
  template:
    metadata:
      labels:
        app.kubernetes.io/component: main
        app.kubernetes.io/instance: qbittorrent
        app.kubernetes.io/name: qbittorrent
    spec:
      enableServiceLinks: false
      serviceAccountName: default
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      hostIPC: false
      hostNetwork: false
      hostPID: false
      dnsPolicy: ClusterFirst
      containers:
        - name: main
          image: lscr.io/linuxserver/qbittorrent:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/Los_Angeles
            - name: UMASK
              value: "002"
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: webui
              protocol: TCP
            - containerPort: 6881
              name: bittorrent-tcp
              protocol: TCP
            - containerPort: 6881
              name: bittorrent-udp
              protocol: UDP
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SETUID
                - SETGID
                - CHOWN
              drop:
                - ALL
            runAsGroup: 0
            runAsUser: 0
          startupProbe:
            failureThreshold: 120
            initialDelaySeconds: 10
            periodSeconds: 5
            tcpSocket:
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /media
              name: media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: media
          persistentVolumeClaim:
            claimName: jellyfin-media
