falco:
  driver:
    kind: modern_ebpf

  metrics:
    enabled: true

  falcosidekick:
    enabled: true
    config:
      alertmanager:
        hostport: http://alertmanager-operated.monitoring.svc:9093
        endpoint: /api/v2/alerts
        expiresafter: 10m

  serviceMonitor:
    create: true
    labels:
      release: kube-prometheus-stack

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
