#!/usr/bin/env python3
"""Wrap a Grafana dashboard JSON export into the ConfigMap the sidecar loads.

Dashboards are deployed by the kube-prometheus-stack Grafana sidecar, which
picks up any ConfigMap in `monitoring` labelled `grafana_dashboard: "1"` and
files it under the folder named in the `grafana_folder` annotation. Those
ConfigMaps are the single source of truth: Grafana runs with
`persistence.enabled: false`, so anything edited in the UI is lost on restart
unless it is exported back through here and committed.

Usage:
    scripts/dashboard-to-configmap.py <dashboard.json> --folder VMs --name vms-jellyfin
"""
import argparse
import json
import pathlib
import sys

TEMPLATE = """---
# Generated by scripts/dashboard-to-configmap.py -- edit the dashboard in
# Grafana, export the JSON, and re-run this rather than hand-editing the file.
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-{name}
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
  annotations:
    grafana_folder: "{folder}"
data:
  {filename}: |
{body}
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("dashboard", type=pathlib.Path)
    ap.add_argument("--folder", required=True, help='Grafana folder, e.g. "VMs"')
    ap.add_argument("--name", required=True, help="suffix after grafana-dashboard-")
    ap.add_argument("--filename", help="key inside data: (default: <last-name-segment>.json)")
    ap.add_argument("--version", type=int,
                    help="set an explicit dashboard version (default: input version + 1)")
    ap.add_argument("--keep-version", action="store_true",
                    help="do not touch the version field")
    ap.add_argument("-o", "--out", type=pathlib.Path)
    a = ap.parse_args()

    # Parse rather than copy blindly: a malformed export should fail here and
    # not silently land in the cluster as a dashboard Grafana refuses to render.
    try:
        parsed = json.loads(a.dashboard.read_text())
    except json.JSONDecodeError as e:
        print(f"error: {a.dashboard} is not valid JSON: {e}", file=sys.stderr)
        return 1
    if not isinstance(parsed, dict):
        print(f"error: {a.dashboard} is not a JSON object; is it a dashboard export?", file=sys.stderr)
        return 1
    # Check the type, not just presence. "panels": {} or "panels": null both pass
    # a bare `in` test and would be written out as a dashboard Grafana refuses to
    # render -- with null also crashing this script after the file was written.
    if not isinstance(parsed.get("panels"), list):
        got = type(parsed.get("panels")).__name__ if "panels" in parsed else "absent"
        print(f"error: {a.dashboard} 'panels' must be a list, got {got}; is it a dashboard export?",
              file=sys.stderr)
        return 1

    # Grafana's file provisioner will not overwrite a dashboard that has been
    # edited in the UI unless the file's version is higher than the stored one,
    # and allowUiUpdates is true here. A Grafana export carries the current
    # stored version, so incrementing it is what makes this ConfigMap win.
    if a.version is not None:
        parsed["version"] = a.version
    elif not a.keep_version:
        current = parsed.get("version")
        parsed["version"] = (current if isinstance(current, int) else 0) + 1

    filename = a.filename or f"{a.name.split('-')[-1]}.json"
    body = "\n".join("    " + line for line in json.dumps(parsed, indent=2).splitlines())
    out_text = TEMPLATE.format(name=a.name, folder=a.folder, filename=filename, body=body)

    dest = a.out or pathlib.Path(
        f"infrastructure/monitoring/grafana-dashboards/grafana-dashboard-{a.name}.yaml"
    )
    dest.write_text(out_text)
    print(f"wrote {dest} ({len(parsed['panels'])} panels, version {parsed.get('version')})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
