---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook-url
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-infrastructure
    kind: ClusterSecretStore
  target:
    name: discord-webhook-url
    creationPolicy: Owner
  data:
    - secretKey: webhook-url
      remoteRef:
        key: "vausmfy2q2m57r6scvziyrc7lq/credential"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
