---
apiVersion: v1
kind: Service
metadata:
  name: discord-alert-proxy
  namespace: monitoring
spec:
  selector:
    app: discord-alert-proxy
  ports:
    - port: 9095
      targetPort: 9095
  type: ClusterIP
