---
# RuntimeClass for NVIDIA GPU workloads
# Optional: Use if you want to explicitly specify the nvidia runtime
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
handler: nvidia
