resources:
  - ../../infrastructure/metallb
  - ../../infrastructure/nfs
  - ../../infrastructure/nvidia
  - ../../infrastructure/monitoring
  - ../../infrastructure/external-secrets
  - ../../apps/media