resources:
  - ../../infrastructure/metallb
  - ../../infrastructure/nfs

  - ../../infrastructure/monitoring
  - ../../infrastructure/external-secrets
  - ../../infrastructure/reloader
  - ../../infrastructure/security
  - ../../apps/media